spring.application.name=MyExampleApp
<<<<<<< HEAD

server.port=8081

spring.profiles.active=dev,prod

# mvn spring-boot:run "-Dspring.profiles.active=dev"
=======
server.port=8081
spring.profiles.active=dev
>>>>>>> c353784 (some changes)
